export const integrationsList: IntegrationData[] = [
  {
    id: 1,
    title: "Youtube",
    platformType: "Plataforma de vídeo",
    imageSrc: "/images/ytb.png",
  },
  {
    id: 2,
    title: "Vimeo",
    platformType: "Plataforma de vídeo",
    imageSrc: "/images/vimeo.png",
  },
  {
    id: 3,
    title: "Hotmart",
    platformType: "Plataforma de cursos",
    imageSrc: "/images/hotmart.png",
  },
  {
    id: 4,
    title: "Kiwify",
    platformType: "Plataforma de infoprodutos",
    imageSrc: "/images/kiwify.jpg",
  },
  {
    id: 5,
    title: "Kirvano",
    platformType: "Plataforma de infoprodutos",
    imageSrc: "/images/kirvano.png",
  },
  {
    id: 6,
    title: "Ticto",
    platformType: "Plataforma de infoprodutos",
    imageSrc: "/images/ticto.png",
  },
  {
    id: 7,
    title: "CartPanda",
    platformType: "Plataforma de e-commerce",
    imageSrc: "/images/cartpanda.avif",
  },
  {
    id: 8,
    title: "Yampi",
    platformType: "Plataforma de e-commerce",
    imageSrc: "/images/yampi.png",
  },
  {
    id: 9,
    title: "Cakto",
    platformType: "Plataforma de pagamentos",
    imageSrc: "/images/cakto.png",
  },
  {
    id: 10,
    title: "Monettize",
    platformType: "Plataforma de infoprodutos",
    imageSrc: "/images/monettize.png",
  },
  {
    id: 11,
    title: "Vturb",
    platformType: "Plataforma de marketing",
    imageSrc: "/images/vturb.jpeg",
  },
  {
    id: 12,
    title: "PandaVideo",
    platformType: "Plataforma de vídeo",
    imageSrc: "/images/pandavideo.png",
  },
  {
    id: 13,
    title: "Digital Manager Guru",
    platformType: "Plataforma de gestão",
    imageSrc: "/images/guru.webp",
  },
  {
    id: 14,
    title: "AppMax",
    platformType: "Plataforma de pagamentos",
    imageSrc: "/images/appmax.png",
  },
  {
    id: 15,
    title: "Perfect Pay",
    platformType: "Plataforma de pagamentos",
    imageSrc: "/images/perfectpay.jpeg",
  },
];
