import type { Product } from "types/product";

export const products: Product[] = [
  {
    id: "1",
    isCertificate: true,
    name: "Curso de Programação Web",
    urlThumbCourse: "https://example.com/web-course-thumbnail.jpg",
    description:
      "Aprenda a criar aplicações web completas com HTML, CSS, e JavaScript.",
    category: ["Programação", "Desenvolvimento Web"],
    duration: "10h",
    delDate: null,
    producerId: "producer1",
    state: "PUBLICO",
    createdAt: "2024-12-01T10:00:00Z",
    updatedAt: "2024-12-10T15:00:00Z",
    modules: [
      {
        id: "module1",
        stateModule: "PUBLICO",
        name: "Introdução à Programação Web",
        description: "Conceitos básicos e configuração do ambiente de desenvolvimento.",
        delDate: null,
        channelIdChanged: "channel123",
        playlistIdChanged: null,
        courseYtId: "ytcourse123",
        createdAt: "2024-12-01T10:30:00Z",
        updatedAt: "2024-12-01T10:30:00Z",
        lessons: [
          {
            createdAt: "2024-12-01T10:35:00Z",
            description: "Introdução ao curso e overview da programação web.",
            id: "lesson1",
            idLessonYt: "ytlesson101",
            nameLesson: "Introdução ao Curso",
            thumbnails: "https://example.com/thumb1.jpg",
            updatedAt: "2024-12-01T10:35:00Z",
            urlVideoYt: "https://youtube.com/video101",
            youtubeCourseId: "ytcourse123",
          },
          {
            createdAt: "2024-12-01T10:50:00Z",
            description: "Configuração do ambiente de desenvolvimento.",
            id: "lesson2",
            idLessonYt: "ytlesson102",
            nameLesson: "Configuração do Ambiente",
            thumbnails: "https://example.com/thumb2.jpg",
            updatedAt: "2024-12-01T10:50:00Z",
            urlVideoYt: "https://youtube.com/video102",
            youtubeCourseId: "ytcourse123",
          },
        ],
      },
      {
        id: "module2",
        stateModule: "PUBLICO",
        name: "HTML e CSS",
        description: "Estruturando e estilizando páginas web.",
        delDate: null,
        channelIdChanged: "channel123",
        playlistIdChanged: null,
        courseYtId: "ytcourse123",
        createdAt: "2024-12-02T11:00:00Z",
        updatedAt: "2024-12-02T11:00:00Z",
        lessons: [
          {
            createdAt: "2024-12-02T11:05:00Z",
            description: "Estruturando páginas com HTML.",
            id: "lesson3",
            idLessonYt: "ytlesson103",
            nameLesson: "HTML Básico",
            thumbnails: "https://example.com/thumb3.jpg",
            updatedAt: "2024-12-02T11:05:00Z",
            urlVideoYt: "https://youtube.com/video103",
            youtubeCourseId: "ytcourse123",
          },
          {
            createdAt: "2024-12-02T11:20:00Z",
            description: "Estilizando com CSS.",
            id: "lesson4",
            idLessonYt: "ytlesson104",
            nameLesson: "CSS Básico",
            thumbnails: "https://example.com/thumb4.jpg",
            updatedAt: "2024-12-02T11:20:00Z",
            urlVideoYt: "https://youtube.com/video104",
            youtubeCourseId: "ytcourse123",
          },
        ],
      },
    ],
  },
  {
    id: "2",
    isCertificate: false,
    name: "Curso de Design Gráfico",
    urlThumbCourse: "https://example.com/graphic-design-course-thumbnail.jpg",
    description:
      "Explore técnicas de design gráfico e crie peças visuais incríveis.",
    category: ["Design", "Criatividade"],
    duration: "8h",
    delDate: null,
    producerId: "producer2",
    state: "PRIVADO",
    createdAt: "2024-11-15T14:00:00Z",
    updatedAt: "2024-12-01T14:30:00Z",
    modules: [
      {
        id: "module3",
        stateModule: "PRIVADO",
        name: "Introdução ao Design Gráfico",
        description: "Fundamentos do design gráfico e ferramentas básicas.",
        delDate: null,
        channelIdChanged: "channel456",
        playlistIdChanged: null,
        courseYtId: "ytcourse456",
        createdAt: "2024-11-15T14:10:00Z",
        updatedAt: "2024-11-15T14:10:00Z",
        lessons: [
          {
            createdAt: "2024-11-15T14:15:00Z",
            description: "História do design gráfico.",
            id: "lesson5",
            idLessonYt: "ytlesson201",
            nameLesson: "História do Design",
            thumbnails: "https://example.com/thumb5.jpg",
            updatedAt: "2024-11-15T14:15:00Z",
            urlVideoYt: "https://youtube.com/video201",
            youtubeCourseId: "ytcourse456",
          },
          {
            createdAt: "2024-11-15T14:30:00Z",
            description: "Apresentação de ferramentas essenciais.",
            id: "lesson6",
            idLessonYt: "ytlesson202",
            nameLesson: "Ferramentas Essenciais",
            thumbnails: "https://example.com/thumb6.jpg",
            updatedAt: "2024-11-15T14:30:00Z",
            urlVideoYt: "https://youtube.com/video202",
            youtubeCourseId: "ytcourse456",
          },
        ],
      },
      {
        id: "module4",
        stateModule: "PRIVADO",
        name: "Tipografia e Cores",
        description: "Compreendendo tipografia e teoria das cores no design.",
        delDate: null,
        channelIdChanged: "channel456",
        playlistIdChanged: null,
        courseYtId: "ytcourse456",
        createdAt: "2024-11-16T09:00:00Z",
        updatedAt: "2024-11-16T09:00:00Z",
        lessons: [
          {
            createdAt: "2024-11-16T09:10:00Z",
            description: "Princípios básicos de tipografia.",
            id: "lesson7",
            idLessonYt: "ytlesson203",
            nameLesson: "Tipografia Básica",
            thumbnails: "https://example.com/thumb7.jpg",
            updatedAt: "2024-11-16T09:10:00Z",
            urlVideoYt: "https://youtube.com/video203",
            youtubeCourseId: "ytcourse456",
          },
          {
            createdAt: "2024-11-16T09:30:00Z",
            description: "Introdução à teoria das cores.",
            id: "lesson8",
            idLessonYt: "ytlesson204",
            nameLesson: "Teoria das Cores",
            thumbnails: "https://example.com/thumb8.jpg",
            updatedAt: "2024-11-16T09:30:00Z",
            urlVideoYt: "https://youtube.com/video204",
            youtubeCourseId: "ytcourse456",
          },
        ],
      },
    ],
  },
];
